
@startuml DigdemClientSide
left to right direction
actor Client as g

package GybingFxTrading {
  usecase "New User Register" as UC1
  usecase "Login" as UC2
  usecase "Execute Trade" as UC3
  usecase "Execute Trade" as UC4
  usecase "Open New Account" as UC5
  usecase "Update Account" as UC6
  usecase "Delete Account" as UC7
  usecase "Update Settings" as UC8
  usecase "View Trade History" as UC9
  usecase "Export File" as UC10

}

g --> UC1
g --> UC2
g --> UC3
g --> UC4
g --> UC5
g --> UC6
g --> UC7
g --> UC8
g --> UC9
g --> UC10
@enduml
